package com.society.controller;

import com.society.dto.request.OtpVerificationRequest;
import com.society.dto.request.RegisterRequest;
import com.society.dto.response.ApiResponse;
import com.society.dto.response.AuthResponse;
import com.society.service.AuthService;
import com.society.util.PhoneMaskUtil;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/auth")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "1. Authentication", description = "Secure OTP-based authentication via Twilio Verify API")
public class AuthController {

    private final AuthService authService;

    /**
     * Register a new user
     * Public endpoint - no authentication required
     */
    @PostMapping("/register")
    @Operation(
            summary = "Register a new user",
            description = "Register Rental, Manager, Owner, or Security Guard. " +
                    "After registration, use /auth/login to receive OTP."
    )
    public ResponseEntity<ApiResponse<String>> register(@Valid @RequestBody RegisterRequest request) {
        log.info("Registration request received for role: {}", request.getRole());
        String message = authService.register(request);
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(ApiResponse.success(message, null));
    }

    /**
     * Send OTP to registered phone number
     * Uses Twilio Verify API (OTP generated by Twilio, NOT backend)
     * Rate limited: 3 requests per 5 minutes per phone
     */
    @PostMapping("/login")
    @Operation(
            summary = "Send OTP via Twilio Verify",
            description = "Sends a 6-digit OTP to the registered phone number via SMS. " +
                    "OTP is generated, stored, and expired by Twilio. " +
                    "Rate limit: 3 requests per 5 minutes per phone number."
    )
    public ResponseEntity<ApiResponse<String>> login(@RequestParam String phoneNo) {
        //Mask phone in logs (security)
        log.info("OTP request for phone: {}", PhoneMaskUtil.mask(phoneNo));

        //Call secure sendOtp (returns String message, not AuthResponse)
        String message = authService.sendOtp(phoneNo);

        return ResponseEntity.ok(ApiResponse.success(message, null));
    }

    /**
     * Resend OTP to phone number
     * Optional endpoint - useful if user didn't receive first OTP
     */
    @PostMapping("/resend-otp")
    @Operation(
            summary = "Resend OTP via Twilio Verify",
            description = "Resends OTP if the first one was not received or expired."
    )
    public ResponseEntity<ApiResponse<String>> resendOtp(@RequestParam String phoneNo) {
        log.info("Resend OTP request for: {}", PhoneMaskUtil.mask(phoneNo));
        String message = authService.sendOtp(phoneNo);
        return ResponseEntity.ok(ApiResponse.success(message, null));
    }

    /**
     * Verify OTP and get JWT token
     * Uses Twilio Verify API (validation done by Twilio, NOT backend)
     * Rate limited: 5 attempts per 5 minutes per phone
     */
    @PostMapping("/verify-otp")
    @Operation(
            summary = "Verify OTP and receive JWT token",
            description = "Verifies the 6-digit OTP via Twilio. " +
                    "On success, returns JWT token and user details. " +
                    "Rate limit: 5 attempts per 5 minutes per phone number."
    )
    public ResponseEntity<ApiResponse<AuthResponse>> verifyOtp(
            @Valid @RequestBody OtpVerificationRequest request) {

        //Mask phone in logs
        log.info("OTP verification attempt for: {}",
                PhoneMaskUtil.mask(request.getPhoneNo()));

        AuthResponse response = authService.verifyOtpAndLogin(request);

        log.info("Login successful for user ID: {}", response.getUserId());

        return ResponseEntity.ok(ApiResponse.success("Login successful", response));
    }

    /**
     * Logout endpoint
     * Since we use JWT, logout is handled client-side by clearing the token
     * This endpoint can be used for logging purposes
     */
    @PostMapping("/logout")
    @SecurityRequirement(name = "bearerAuth")
    @Operation(
            summary = "Logout (client-side token removal)",
            description = "JWT is stateless, so logout is handled by the client. " +
                    "This endpoint is provided for logging purposes."
    )
    public ResponseEntity<ApiResponse<String>> logout() {
        log.info("User logged out");
        return ResponseEntity.ok(ApiResponse.success(
                "Logged out successfully. Please clear your token on the client side.",
                null
        ));
    }
}
